"""empty message

Revision ID: acdfde5b4a3
Revises: None
Create Date: 2015-09-13 23:20:13.529326

"""

# revision identifiers, used by Alembic.
revision = 'acdfde5b4a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    ### end Alembic commands ###
